spring.application.name=api-gateway
# Run the Gateway on port 8080 (Angular will send all requests here!)
server.port=8080
# Tell the Gateway where to find the Eureka Server we just built
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# Force the instance to identify itself by its hostname, which Render resolves correctly
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
# MAGIC: Automatically create routes for every microservice registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*
